#!/usr/bin/env ruby

# Bring OptionParser into the namespace
require 'optparse'

options = {}
options_parser = OptionParser.new  do |opts|

  # Create a switch
  opts.on("-i","--iteration") do
    options[:iteration] = true
  end

  # Create a flag
  opts.on("-u USER",/^.+\..+$/) do |user|
    options[:user] = user
  end

  opts.on("-p PASSWORD") do |password|
    options[:password] = password
  end

  # Valid Servers
  servers = {'dev' => '127.0.0.1',
              'qa' => 'qa001.example.com',
              'prod' => 'www.example.com' }

  # Using hashes for validation check and send values of keys to code block
  opts.on('--server SERVER',servers) do |address|
    options[:address] = address
  end
end

options_parser.parse!
puts options.inspect

#database = ARGV.shift
#username = ARGV.shift
#password = ARGV.shift
#
#end_of_iter = ARGV.shift
#
#
#if end_of_iter.nil?
#  backup_file = database + '_' + Time.now.strftime("%Y%m%d")
#else
#  backup_file = database + '_' + end_of_iter
#end
#
#`mysqldump -u#{username} -p#{password} #{database} > #{backup_file}.sql`
#`gzip #{backup_file}.sql`

