#!/usr/bin/env ruby

# Bring OptionParser into the namespace
require 'optparse'

options = {}
options_parser = OptionParser.new  do |opts|

  # Create a switch
  opts.on("-i ITER","--iteration", /^\d+$/) do |iter_no|
    options[:iteration] = true
    options[:iter_no] = iter_no
  end

  opts.on("-u USER") do |user|
    options[:user] = user
  end

  opts.on("-p PASSWORD") do |password|
    options[:password] = password
  end
end

options_parser.parse!
puts options.inspect

database = ARGV.shift 

if database.nil?
  raise ArgumentError,"Database not provided"
end

if options[:iteration]
  backup_file = database + '_iteration_' + options[:iter_no]
else
  backup_file = database + '_' + Time.now.strftime("%Y%m%d")
end

`mysqldump -u#{options[:user]} -p#{options[:password]} #{database} > #{backup_file}.sql`
`gzip #{backup_file}.sql`

